### ISSUE TITLE
lets talk about a linux client :)

### ISSUE THREAD

**Issue by fishxz** [AndreyNazarov/q2pro#100]
hey,
im testing from time to time ubuntu with q2pro as client, but the experience is not the best.

- with compiz, q2pro runs unsmooth. it feels like low fps (a year ago i tried with disabled compiz and as far i remember q2pro runs great then)
- if i window/minimize q2pro the whole desktop works slow, unless i quit q2pro. it is also not possible to tab out like on windows. you always need to window it, to can minimize.
- the keyboard layout is not made for other languages than english. you always need to switch to english layout for playing quake2. quake2 on windows switch automatically to english layout ingame.

other than that, q2pro runs fine there :)

**Comment by amokmen** [comment]
> it is also not possible to tab out like on windows
Could you try to drop down gameconsole and then alt+tab?

**Comment by fishxz** [comment]
nope, doesnt work. the weird fps feeling seems to be fixed by disabling vsync in nvidia driver.

but keyboardlayout and minimizing like in windows would be also nice :)

**Comment by fishxz** [comment]
sdl2 seems to fixed all my problem at once. 

- even with vsync it runs fine
- keyboard layout is switching
- alt tabbing works
