### ISSUE TITLE
Q2pro.menu fix binds and server's search

### ISSUE THREAD

**Issue by PowaBanga** [AndreyNazarov/q2pro#108]
Hi,
I am writting a q2pro.menu for dday mod. And there is some shout, who change every time with alias. The sound change every time when you push on a key.
So here, I am writting the key binding in q2menu, and I can't fix that, this code don't work
```
begin shouts
bind "Cover" c1
alias c1 "shout cover1;wave 0; bind F4 c2"
alias c2 "shout cover2;wave 0; bind F4 c3"
alias c3 "shout cover3;wave 0; bind F4 c1"
end
```
There is a way to fix that ?

My second question is about servers in q2pro menu.
I found this : 
```
    action "Referenced servers" pushmenu servers "+http://q2servers.com/?g=dday&raw=2"
    action "Browse address book" pushmenu servers "favorites://" "file:///servers.lst" "broadcast://"
```
So here, I have one bouton for look in a file, an other for look on Q2servers. My question is : can I create a buton to look on all local ip if there is a new server launcher by a friend who is in the same home of me ?

**Comment by PowaBanga** [comment]
I finaly found a way for the first problem. I wrotte this in autoexec.cfg 
```
alias vv "v1"
alias v1 "shout thanks1; wave 1; alias vv "v2""
alias v2 "shout thanks2; wave 1; alias vv "v1""
```
and this in Q2pro.menu : 
```
begin shouts
bind "thanks" vv
end
```
rest my question about local servers :)

**Comment by amokmen** [comment]
I think this is answer for your second question --> "broadcast://"

Broadcast means that your client sends (or recieves? I don't know exactly how it works) messages for each network device (in your subnet of course) and waits answer. If there is running server, server answers and your client now know server's IP.

**Comment by PowaBanga** [comment]
ok i will look when my friend come back. And "favorites://" what is it exactly ?

**Comment by amokmen** [comment]
Probably "Address book"

**Comment by PowaBanga** [comment]
problem solved for me
