### ISSUE TITLE
What is a MVD/GTV client ?

### ISSUE THREAD

**Issue by PowaBanga** [AndreyNazarov/q2pro#113]
Hi all, is ther this in .config documentation:
```
# Enable local MVD recording and MVD/GTV server functionality. Use this for
# hosting a GTV-capable game server.
#CONFIG_MVD_SERVER=y

# Enable MVD/GTV client functionality. Use this for hosting a GTV relay server.
#CONFIG_MVD_CLIENT=y
```
But maybe it's because my english is not good, but I don't understand what is it...
Does it work on linux ? Because I have errors in compilation...

**Comment by m4son** [comment]
A player can stream his POV(Point Of View) to a MVD server where  milions of people can connect and watch his gameplay :)

**Comment by PowaBanga** [comment]
haa ok thanks you
