### ISSUE TITLE
q2pro menu -> how to exit menu&launch command

### ISSUE THREAD

**Issue by PowaBanga** [AndreyNazarov/q2pro#116]
Hi all.
I writting q2pro.menu for dday, and I want do in sort that, when I am in game, in the menu who appear when I type on `ESC` have a line who exit the menu &/or launch a game command

Something like this :
```
begin game
    background #001A1750
    style --compact
    push "Join the game" menu_main
    push "Observer mode" observer
    blank
    action "Servers" pushmenu servers 
    action "demos" pushmenu demos
    action "options" pushmenu options
    action "disconnect" disconnect
    action "quit" quit
end
```
There is a way to do that ?

**Comment by m4son** [comment]
If i understand correct You want something like this...
action "Some action" commandX;forcemenuoff

**Comment by PowaBanga** [comment]
Thanks you it was that I looked for :)
