### ISSUE TITLE
making chat lines in log more visible, to grep them?

### ISSUE THREAD

**Issue by fishxz** [AndreyNazarov/q2pro#120]
hey, i want to tail the chat to a discord channel, but there is no easy way to filter just the chat lines using grep, because the chatlines are not unique to other lines.

**Comment by m4son** [comment]
Some people once said, RTFM, well yes indeed.

Lets look what docs say...


~~~~~~~~~~~~~~~

logfile::
    Specifies if console logging to file is enabled. Default value is 0.
      - 0 — logging disabled
      - 1 — logging enabled, overwrite previous file
      - 2 — logging enabled, append to previous file

NOTE: Log file is not automatically reopened when game directory is changed.

logfile_flush::
    Specifies if log file data is buffered in memory or flushed to disk
    immediately. Default value is 0. See setvbuf(3) manual page for more
    details.
      - 0 — system default mode (block buffered)
      - 1 — line buffered mode
      - 2 — unbuffered mode

logfile_name::
    Specifies base name of the log file. Should not include any extension part
    or path components. ‘logs/’ prefix and ‘.log’ suffix are automatically
    appended.  Default value is ‘console’.

logfile_prefix::
    Specifies the time/date template each line of log file is prefixed with.
    Default value is ‘[%Y-%m-%d %H:%M] ’. See strftime(3) manual page for
    syntax description. In addition, the first ‘@’ character in the template,
    if found, is replaced with a single character representing message type
    (T — talk, D — developer, W — warning, E — error, N — notice, A — default).
~~~~~~~~~~~~~~~

So, use of

> logfile_flush "2"
> logfile "2"
> logfile_prefix "@ [%Y-%m-%d %H:%M] "

gives You a result that can be used with grep easily.

**Comment by amokmen** [comment]
@m4son answered question, but too long :)

@fishxz, I just checked console.log from my OpenFFA mod, and there are special labels for chat lines:
_N [2016-05-27 19:06:18] q2proded r1504~924ff39, Dec  3 2014
A [2016-05-27 19:06:18] http://skuller.net/q2pro/
A [2016-05-27 19:08:17] Player entered the game (1 player)
A [2016-05-27 19:11:18] 10 minutes remaining in match.
T [2016-05-27 19:11:26] Player: Hello!_

See line which starting from letter "T"? This is chat line. 

I did it with such **config string**:
_set logfile_prefix "**@** [%Y-%m-%d %H:%M:%S] "_

See "@" at start of template? That is what you seeking.

**Comment by fishxz** [comment]
thanks. i have read the server manual like 100 times over the years, especially the log part and i never noticed this part.
